model: tam-rl
split_type: Koppen
best_params:
  hidden_dim: 128
  latent_dim: 32
  dropout: 0.3
  lr: 0.0001
  layers: 1
cv_r2_mean: 0.3879685748006825
cv_r2_std: 0.0153940680831592
cv_rmse_mean: 1.7357258917745173
